### ISSUE TITLE
rustc --explain E0554

### ISSUE THREAD

**Issue by steamsv** [branlwyd/rspd#2]
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:12
  |
1 | #![feature(vec_spare_capacity)]
  |            ^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `rspd` due to previous error

**Comment by branlwyd** [comment]
`rspd` currently only compiles in the `nightly` release channel (AFAIK, I have not tried the `beta` channel lately) -- see https://rust-lang.github.io/rustup/concepts/channels.html for information on how to compile something using a non-`stable` channel.
