### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by aiguy110** [branlwyd/rspd#3]
Hi @branlwyd! It doesn't look like you're actively developing this project anymore. Would you consider adding a license to it so I can tell if it would be appropriate for me to fork this for my own purposes, or if I need to start from scratch? MIT would be appreciated, but of course that is up to you :smile:

**Comment by branlwyd** [comment]
Done: this project is now MIT-licensed. Feel free to fork it, or use it in any other license-compliant way. :)
